apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'lmgomez.saavedra@gmail.com'
      smtp_auth_username: 'lmgomez.saavedra@gmail.com'
      smtp_auth_password: 'favhnrbmispkkvdm'
    route:
      receiver: email
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 2h
    receivers:
      - name: email
        email_configs:
          - to: 'lmgomez.saavedra@gmail.com'
