version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-customer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - customer-network

volumes:
  postgres_data:

networks:
  customer-network:
    driver: bridge
