apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quarkus-datasource-rule
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  groups:
    - name: datasource.rules
      rules:
        - alert: QuarkusDatasourceDown
          expr: custom_health_datasource_status == 0
          for: 5s
          labels:
            severity: critical
            #team: quarku #lo marco para solo enviar este tipo de alertas a un canal específico
          annotations:
            summary: "Datasource caído en el pod {{ $labels.pod }}"
            description: "La base de datos está caída. Datasource: {{ $labels.datasource }} - Pod: {{ $labels.pod }} - Namespace: {{ $labels.namespace }}"
