apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-servicemonitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
      metricRelabelings:
        - targetLabel: application
          replacement: my-quarkus-app
      relabelings:
        - targetLabel: application
          replacement: my-quarkus-app
        - sourceLabels: [ application ]
          targetLabel: job
  namespaceSelector:
    matchNames:
      - applications
